baseURL = "http://offresemploi.nc/"
languageCode = "fr"
title = "Offres d'Emploi Calédonie"
theme = "emplois-materialize"
disableKinds = ["taxonomy", "taxonomyTerm"]
# Define the number of posts per page
paginate = 10

[menu]


# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    identifier="About"
    name = "A propos"
    url  = "#About"
    weight = 2

[[menu.main]]
    identifier = "faq"
    name = "Faq"
    url  = "#FAQ"
    weight = 3

[[menu.main]]
    identifier = "team"
    name = "Equipe"
    url  = "#TEAM"
    weight = 4

[[menu.main]]
    identifier = "store"
    name = "Télécharger"
    url  = "#STORE"
    weight = 5

[[menu.main]]
    identifier = "contact"
    name = "Contact"
    url  = "#CONTACT"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]

    # Social media
    facebook_site = ""
    twitter_site = "GoHugoIO"

    email = "your@email.com"
    contact_form_ajax = false

    contact_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"

    copyright = "Copyright (c) 2000, Offres Emploi Calédonie; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo_small.png"
    logo_small = "img/logo_small.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.main]
    enable = true

[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.see_more]
    enable = true
    icon = "fab fa-google-play"
    title = "Télécharger l'application sur le Play Store"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "fab fa-google-play"
    size_icon = "fa-3x"
    
[params.faq]
    enable = true
    title = "FAQ"
[params.morefaq]
    enable = true
    title = "MOREFAQ"

[params.team]
    enable = true
    title = "Notre Equipe"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."



[params.clients]
    enable = true
    title = "Rejoignez-nous"
    subtitle = ""

[params.about]
    enable = true
    title = "A Propos"
    text = """ Nous développons un écosystème complet et Open source autour des Offres d'emploi en Nouvelle-Calédonie. Le but
    est de mettre en oeuvre, gratuitement, et avec du logiciel Open Source des services packagés comme le font les géants du Web.

    Nous croyons fermement que cette ouverture permettra la création de nouvelles innovations pour notre pays.

    Pour cela nous avons:

    Créé un SDK (https://jitpack.io/#adriens/emploi-nc-sdk) qui permet d'interagir efficacement avec le site des Offres d'Emploi du Gouvernement de Nouvelle-Calédonie
    
    Développé une API REST (https://github.com/adriens/emploi-nc-api) qui utilise le SDK

    Déployé sur Heroku et mis à disposition cette API sur le Marketplace d'APIS (https://rapidapi.com/adriens/api/emploi-nouvelle-caledonie)
 
    Développé une application mobile qui permettra aux calédoniens de consulter des offres emplois où qu'ils soit et offrir de nouveaux services"""

