baseURL = "http://offresemploi.nc/"
languageCode = "fr"
title = "Offres d'Emploi Calédonie"
theme = "emplois-materialize"
disableKinds = ["taxonomy", "taxonomyTerm"]
# Define the number of posts per page
paginate = 10

[menu]


# Main menu

[[menu.main]]
    identifier="home"
    name = "Home"
    url  = "https://adriens.github.io/emploi-nc-website"
    weight = 1

[[menu.main]]
    identifier="About"
    name = "A propos"
    url  = "#About"
    weight = 2

[[menu.main]]
    identifier = "faq"
    name = "Faq"
    url  = "#FAQ"
    weight = 3

[[menu.main]]
    identifier = "team"
    name = "Equipe"
    url  = "#TEAM"
    weight = 4

[[menu.main]]
    identifier = "store"
    name = "Télécharger"
    url  = "#STORE"
    weight = 5
[[menu.main]]
    identifier = "Made"
    name = "Made"
    url  = "https://adriens.github.io/emploi-nc-website/made"
    weight = 6

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Facebook"
    url = "http://facebook.com"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Twitter"
    url = "http://twitter.com"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:your@email.com"
    pre = "<i class='fas fa-2x fa-envelope'></i>"

[params]

    # Social media
    facebook_site = ""
    twitter_site = "GoHugoIO"

    email = "your@email.com"
    contact_form_ajax = false

    contact_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"

    copyright = "Copyright (c) 2000, Offres Emploi Calédonie; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/logo_small.png"
    logo_small = "img/logo_small.png"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

[params.main]
    enable = true

[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
      </p>
      """

[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true

[params.see_more]
    enable = true
    icon = "fab fa-google-play"
    title = "Télécharger l'application sur le Play Store"
    subtitle = "L'application est désormais disponible sur le google Play Store."
    link_url = "https://play.google.com/store/apps/details?id=com.github.adriens.nc.emploi"
    link_text = "fab fa-google-play"
    size_icon = "fa-3x"
    
[params.faq]
    enable = true
    title = "FAQ"
[params.morefaq]
    enable = true
    title = "MOREFAQ"

[params.team]
    enable = true
    title = "Notre Equipe"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.clients]
    enable = true
    title = "Rejoignez-nous"
    subtitle = ""

[params.about]
    enable = true
    title = "A Propos"
    text = """ Notre ambition est de construire et de mettre à disposition du plus grand nombre un écosystème complet et Open
     source autour des Offres d'emploi en Nouvelle-Calédonie. Le logiciel est open source. Nous espérons attirer ds utilisateurs
     finaux, des développeurs, des intégrateurs, des étudiants stagiaires qui souhaitent apprendre et progresser tout en participant
     à un produit utile au plus grand nombre, pour nous, les calédoniens."""

[params.techno]
    enable = true
    title = "Nos outils"
    text = """ Notre ambition est de construire et de mettre à disposition du plus grand nombre un écosystème complet et Open
     source autour des Offres d'emploi en Nouvelle-Calédonie. Le logiciel est open source. Nous espérons attirer ds utilisateurs
     finaux, des développeurs, des intégrateurs, des étudiants stagiaires qui souhaitent apprendre et progresser tout en participant
     à un produit utile au plus grand nombre, pour nous, les calédoniens."""

[params.footer]
    enable = true
    store_url = "https://play.google.com/store/apps/details?id=com.github.adriens.nc.emploi"
    sdk_github_url = "https://github.com/adriens/emploi-nc-sdk"
    api_github_url = "https://github.com/adriens/emploi-nc-api"
    app_github_url = "https://github.com/adriens/emploi-nc-app"
    website_github_url = "https://github.com/adriens/emploi-nc-website"
    ytbe_url= "https://www.youtube.com/playlist?list=PLVaySOddZPMer1H6o234RyWhEfSThuYW5"
    twitter_url = "https://twitter.com/NcEmploi" 